### ISSUE TITLE
Proposal: Functions

### ISSUE THREAD

**Issue by bigyihsuan** [bigyihsuan/International-Phonetic-Esoteric-Language#1]
**Proposed Syntax:**
```
ʢ name ʡ ʕ code ʔ
EITHER
( name ) { code }
```
**Calling a Function:**
```
h name ɥ
EITHER
[ name ]
```
IPA approach
* Pros: In line with the current control flow structures, has a theme (laryngeals)
* Cons: More IPA to type, hard to distinguish with no whitespace

Bracket approach
* Pros: Easy to read with no whitespace, easy to type
* Cons: Not particularly IPA-ish except for `[]`.

**Comment by lyxal** [comment]
Personally, I think both should be supported. That way, those who want readability can use brackets and those who want to embrace the IPA paradigm can use the IPA symbols.

**Comment by bigyihsuan** [comment]
Problem with having both is that it'd be possible to mix the two, depending on the implementation, which doesn't seem right to me.

**Comment by lyxal** [comment]
In that case, use the IPA symbols

**Comment by bigyihsuan** [comment]
Because GitHub isn't updating the OP:

**Proposed Syntax:**
```
ʢ name ʡʕ code ʔ
```
Characters between the `ʡʕ` are ignored. Whitespace in either field will be stripped. Declaring functions in functions is possible.

**Calling a Function:**
```
{name}
```

**Examples:**
```
ʢ1*2+3ʡʕtθʔAAB{1*2+3}
ʢ1-2/3ʡʕðdʔ[1234][AB][CD]{1-2/3} ; using the number literals in issue #5 
```

**Comment by lyxal** [comment]
I like that. That's a good syntax for functions
