### ISSUE TITLE
Reverse the Stack

### ISSUE THREAD

**Issue by lyxal** [bigyihsuan/International-Phonetic-Esoteric-Language#13]
A single command for stack reversing would be highly appreciated.

**Comment by bigyihsuan** [comment]
* `ɟ (a b c -- c b a)`. REV. Reverses the stack.

Conveniently there was a plosive unused (voiced form of /c/).

# details
- [x] implement instruction (`currentStack.reverse()`)
- [x] test
- [x] commit
- [x] update docs
