### ISSUE TITLE
Add a Register

### ISSUE THREAD

**Issue by lyxal** [bigyihsuan/International-Phonetic-Esoteric-Language#14]
If I want to temporarily store a value, I have to think through using stack mechanics. A register would avoid this.

## Context

[This](https://codegolf.stackexchange.com/questions/206158/what-calculator-is-this-datafile-for) challenge

    i"TI-"ob4hob5ho

Everything is printed on newlines, when it should be on one line. A register means I could concatenate everything together and print like:

    4ɣ

**Comment by lyxal** [comment]
i"TI-"©®4h®5h4ɣ

Where `©` pops the top of stack into the register and `®` retrieves the register

**Comment by bigyihsuan** [comment]
sure why not. also involves cursed `owo`-lang stuff.

* `w (ele -- )`. SETREG. Stores `ele` into the `w`egister.
* `ʍ ( -- ele)`. GETREG. Copies `ele` from the `w`egister.

# details
- [x] implement instructions
- [x] test
- [x] commit and update docs

**Comment by bigyihsuan** [comment]
Though there are 2 value stacks. You could use one stack as the "main" stack and the other one to store values.
