### ISSUE TITLE
A way to input IPEL data from STDIN

### ISSUE THREAD

**Issue by bigyihsuan** [bigyihsuan/International-Phonetic-Esoteric-Language#15]
There is no way of inputting lists. A single string is handled with `i`, ints `ɪ`, and floats `ʏ`. Those last 2 could be merged into one, and `ʏ` be changed to a list input.

# Thoughts
* Copy over code for lists from lexer, or call `Parser.getNextToken()` and `Parser.validateLexemes()` on an input string to return a list.
* Overhead from calling lexer?

# Changes
* `ɪ ( -- value)`. VALUE. Pushes a non-string IPEL value from STDIN. Can push numbers and lists.

**Comment by lyxal** [comment]
A better idea: have an input command that evaluates the input as raw values.

**Comment by bigyihsuan** [comment]
that's a better idea

**Comment by lyxal** [comment]
Recommended order of attempted evaluation: `Float > Integer > List > String`

**Comment by lyxal** [comment]
That is, it tries to take it as a float if possible. If it isn't, it tries it as an integer. If it can't be done, it takes is as a list. If it can't be done, it takes it as a string.

**Comment by bigyihsuan** [comment]
ooo that's good

**Comment by lyxal** [comment]
```python
def nice_input(stack):
    #Take input and best guess what it is the user wants

    temp = input()

    try:
        if type(eval(temp)) is float:
            temp = float(temp)
        elif type(eval(temp)) is int:
            temp = int(temp)
        elif type(eval(temp)) is list:
            temp = eval(temp) 
        else:
            temp = temp
    except:
        temp = temp
    stack.push(temp)


    #Float > Integer > List > String
```

An example of what you may want. Taken from my own little esolang.
